Dockerfile

This container can build snarky! Modification of #19 to fix lingering problems: `bitstring_lib` wanted pkg-config, and beyond that my build directory setup ended up being owned by root.
Closes #18 and resolves #3. The update from the private repo closes #8. This implicitly addresses #5, #12, #14, and #16 too but they'll need their own fixes for non-containerized builds.

Dockerfile: fix typo, missing pkg-config dep, and permissions issue

---

Dockerfile
README.md
bitstring_lib.opam
bitstring_lib/bitstring.ml
bitstring_lib/bitstring.mli
bitstring_lib/jbuild
interval_union.opam
interval_union/interval_union.ml
interval_union/interval_union.mli
interval_union/jbuild
snarky.opam

As noted in #18 , I forgot to include two libraries that we made dependencies of snarky since the last update.
I included them here (`interval_union` and `bitstring_lib`)
I included the Dockerfile @gtank created and modified it to include the two libraries, but I'm getting a strange error in the docker container when I try to build it.
I spent a bit tonight trying to get the Dockerfile to build but I'm not super familiar with opam pinning, just local dune builds. I'm getting a weird error what seems like the end of the build and seems unrelated to the actual ocaml code.
Can anyone help me get this work? cc @nholland94

Add missing deps

---

src/as_prover.ml
src/as_prover.mli
src/as_prover0.ml
src/checked.ml
src/constraint.ml
src/handle.ml
src/provider.ml
src/snark0.ml
src/typ.ml
src/types.ml

This PR pulls out nearly everything from `Snark0` that doesn't explicitly depend on the `Backend` module in some way. Exceptions are:
- `Data_spec.t` and friends
* pulling it out forces us to parametrise over the `Field.t`, `Cvar.t` and `R1CS_constraint_system.t` in the exposed type, which feels particularly un-user-friendly. (Think `('r_var, 'r_value, 'k_var, 'k_value, Field.t, Cvar.t, R1CS_constraint_system.t) t`.)
- `Checked.perform`
* This is the only place where `Checked` depends on `Typ`; it felt cleaner to keep this single definition inline, instead of having a whole module file dedicated to adding in this one function.
@imeckler this is CodaProtocol/coda#1412

Pull everything out of Snarky functors that doesn't depend on Backend

---

.gitattributes

that way github doesn't think our code is 83.8% C++

mark libsnark code as vendored

---

.circleci/config.yml
Makefile

`make build` ensures that the build works
`make examples` ensures that examples build and run

Add CI for Snarky

---

.circleci/config.yml
Makefile
app/reformat-snarky/jbuild
app/reformat-snarky/reformat-snarky.opam
app/reformat-snarky/reformat.ml

This PR
* pulls in `app/reformat` from the coda repo as `app/snarky-reformat`
* implements `make reformat` and `make check-format`
* adds a CI test for `make check-format`, which fixes #42.

Add a formatting check to CI

---

ppx/snarkydef.ml
src/curves.ml
src/merkle_tree.ml
src/snark0.ml

This PR changes the `snarkydef`and `with_label` ppx to output `Snarky.Checked.with_label`, and adds `snarkydef_` and `with_label_` for use inside the Snarky module itself.
This fixes #40.

Add local versions for snarkydef ppx, globally qualify the others

---

.circleci/config.yml
Makefile
src/sha256.ml
src/snark0.ml

With the inline test runner, if the functor isn't instantiated in the same file the tests won't ever get run.
Also adds to CI.

Ensure unit tests are run

---

src/snark_intf.ml

From a question on gitter:
> Howdy! I've been playing around with the election example and have been trying to split up the proving from the verifying. For that, I need to serialize the proof. However, as a OCaml n00b, I'm having trouble understanding how to do that, as the type of the proof `Proof.t` is quite opaque to me. Could anyone help me out here?
This PR includes the backend's `Proof.to_string`/`of_string` functions in the `Snark_intf.Proof` module, to make them easier to find.

Expose Stringable.S on Snark_intf.Proof.t

---

meja/envi.ml
meja/parser_impl.mly
meja/parsetypes.ml
meja/to_ocaml.ml
meja/typechecker.ml

This adds a location to all parts of the AST, so that we can have useful, located error messages later.

Carry locations in the ast

---

meja/meja.ml

This PR adds the `--binml` option to the meja binary, which outputs the OCaml ast as a binary file that `ocamlc` can read.
To use:
```bash
dune exec --root=.. meja/meja.exe -- --binml filename.ml filename.meja && ocamlc filename.ml
```

[Meja] Add --binml to output an ast for the OCaml compiler

---

meja/envi.ml
meja/parser_impl.mly
meja/parsetypes.ml
meja/scripts/run-tests.sh
meja/to_ocaml.ml
meja/typechecker.ml

This PR
* adds `Tpoly`, for instantiating polymorphic variables within types
* uses `Tpoly` as a marker for which type variables to copy when looking up a variable's type
* flattens variable types, removing instantiated variables, before adding a type to the environment
* renames `Tconstr` to `Tctor` (so that `constr` isn't used to refer to type constraints and constructors)
* tweak to the test script to prevent us from clobbering the output ml file if `ocamlformat` fails
These changes should give us enough sophistication in the typechecker and environment to support polymorphic record fields, variants with type constraints, etc. with minimal changes.

[Meja] Add Tpoly for tracking polymorphic variables

---

src/snark0.ml
src/snark_intf.ml

This adds 'xor' for booleans. It's based on the idea of converting a boolean to a sign (0 -> 1, 1 -> -1), multiplying, and then converting back. It costs just one constraint for the multiplication. I replaced 'equal' using 'xor' by the relation `equal x y = not (xor x y)`. It previously cost 2 constraints and now costs 1 since not is free.

add boolean xor and improve equal by one constaint

---

Makefile

This PR changes the default make target to the obvious one (`make build`), so new users can just `make` and have the library build.

Build locally by default when calling `make`

---

src/snark0.ml

This `is_satisfied` call was checking constraints added by `with_constraint_system`. Now that this is no longer available (#72), we can remove the check.

Remove R1CS_constraint_system.is_satisfied call

---

README.md
bench.opam
bitstring_lib.opam
fold_lib.opam
interval_union.opam
meja.opam
ppx_snarky.opam
snarky.opam
tuple_lib.opam

This PR updates the `*.opam` files so that they have the right dependencies and build commands.
Fixes  #78.

Fix opam installation

---

README.md
bench.opam
meja.opam
snarky_bench.opam

This PR
* changes the readme to suggest `opam pin DIR` for installing snarky and deps
* tweaks the opam files so that this works properly

Tweak the opam files, give a better installation method

---

meja/lexer_impl.mll
meja/parser_errors.ml
meja/parser_impl.mly
meja/tests/operator_names.meja
meja/tests/operator_names.ml

This PR adds support for prefix/infix operators, which will let us implement the infix `+`, `*` notations for fields, etc.

[Meja] Add support for prefix/infix operators

---

src/cvar.ml
src/snark0.ml
src/snark_intf.ml

This PR replaces `Var.t` with `int` in `Cvar.t`, which will let us pull a type parameter out of `Typ.t`, `Checked.t` and the interfaces in #92.

Store variable indexes as ints in Cvar.t

---

src/as_prover.ml
src/as_prover.mli
src/as_prover0.ml
src/checked.ml
src/handle.ml
src/provider.ml
src/snark0.ml
src/snark_intf.ml
src/typ.ml
src/typ_monads.ml
src/types.ml

This PR updates the base types so that they no longer refer to `'field_var`/`'cvar`, since we can now just derive that from `'field`.
This affects types `Typ.t`, `Checked.t`, `As_prover.t`, `Typ_monads.Store.t`, `Typ_monads.Read.t` and `Typ_monads.Alloc.t`.

Pull 'field_var out of type parameters

---

examples/election/election.ml
examples/tutorial/tutorial.ml
src/as_prover.ml
src/as_prover.mli
src/as_prover0.ml
src/curves.ml
src/free_monad.ml
src/knapsack.ml
src/merkle_tree.ml
src/monad_let.ml
src/monad_sequence.ml
src/pedersen.ml
src/restrict_monad.ml
src/snark0.ml
src/snark_intf.ml
src/traversable.ml

This PR
* creates the `Monad_let` module matching the interfaces in `Monad.Base`, but also including the `Let_syntax.Let_syntax` module in the toplevel `Let_syntax`
* uses this wherever we have monads
This should remove the need for the e.g. `As_prover.(Let_syntax.(...))` pattern.

Stop needing `open Let_syntax`

---

meja/envi.ml
meja/typechecker.ml

This PR
- adds `Tctor` parameter handling for some cases I'd forgotten to port over
- fixes a nasty typo where both opening *and* closing the scope caused the depth to increase.

[Meja] Handle Tctor parameters everywhere

---

meja/parsetypes.ml

This adds the debug printing function for Meja's internal type representation.
This is mainly so that I don't have to keep `git stash`-ing it when moving between branches. It isn't currently used anywhere.

[Meja] Add a debug printing function for types

---

meja/envi.ml
meja/lexer_impl.mll
meja/parser_impl.mly
meja/parsetypes.ml
meja/tests/implicits-fail.meja
meja/tests/implicits-fail.stderr
meja/tests/implicits.meja
meja/tests/implicits.ml
meja/tests/test_implicits.meja
meja/tests/test_implicits.ml
meja/to_ocaml.ml
meja/typechecker.ml

This PR
- adds the `Timplicit` type for implicit arguments (analogous to `Tarrow`)
- adds the `Unifiable` expression to hold implicit arguments, so that we can unify them
* this uses mutability, so that we don't have to do extra passes over the AST to update it when unifying these variables
- inserts implicit arguments into bindings when the type variables it introduces are contained in those arguments
There is currently no search implemented, so implicit arguments with no type variables (e.g. `testing_show (18) : {testing_show_constr(int)} -> int` in the examples) just get the argument passed through each scope for now.
This depends on #98; without it the test will fail.

[Meja] Implicit arguments

---

examples/imperative_test/imperative_test.ml
src/snark0.ml
src/snark0.mli

This removes the var type parameter in the imperative interface.

remove the var type parameter in the imperative interface

---

examples/elliptic_curve_operations/dune
examples/elliptic_curve_operations/elliptic_curve_operations.ml.ignore
examples/elliptic_curve_operations/elliptic_curve_operations.re

This is a more involved example usage of the imperative API, doing some elliptic curve arithmetic. I don't do any actual generating keys/proving, but that should be added when we land the prettier top level api.
I was thinking this could be a 'pristine' example of 'the new right way' to do things.

ReasonML elliptic curve example

---

meja/lexer_impl.mll
meja/parser_impl.mly
meja/parsetypes.ml
meja/tests/apply-fail.stderr
meja/tests/record_wrong_accessor.meja
meja/tests/record_wrong_accessor.stderr
meja/tests/records.meja
meja/tests/records.ml
meja/tests/test.meja
meja/tests/test.ml
meja/to_ocaml.ml
meja/typechecker.ml

This PR
* adds field accessors
* passes an 'expected type' through `get_expression`, which we use to infer the type of a record for localising its labels correctly
* adds record update syntax `{...x, y: (), z: ()}`
* updates a test that the stricter typechecking broke

Add field accessors

---

src/bool_vector.ml
src/camlsnark_c/libsnark-caml/depends/libff/libff/algebra/fields/fp2.hpp
src/camlsnark_c/libsnark-caml/depends/libff/libff/algebra/fields/fp3.hpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt4_specific.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt6_specific.cpp
src/int_vector.ml
src/libsnark.ml
src/long_vector.ml
src/vector.ml

This cleans up the group bindings, unifying the G1 and G2 bindings. It also adds a Binable instance for vectors.

clean up group bindings

---

src/snark0.ml
src/snark_intf.ml

This PR creates the `Proof_system` interface, currently generalised over all the frontends we expose/are planning to expose, and not exposed in the `snark0.mli` file.
Basic interface structure:
```ocaml
(* The entry point to create a `proof_system` *)
val create :
?proving_key:Proving_key.t ->
?verification_key:Verification_key.t ->
?proving_key_path:string ->
?verification_key_path:string ->
?handler:Request.Handler.t ->
exposing:('checked, unit, 'computation, 'inputs) Data_spec.t ->
'computation ->
('checked, 'inputs, 'state) proof_system
val set_inputs : ('a, 'b, 'c) proof_system -> (unit, 'b) H_list.t -> unit
val clear_inputs : ('a, 'b, 'c) proof_system -> unit
val set_proving_key : ('a, 'b, 'c) proof_system -> Proving_key.t -> unit
val proving_key : ('a, 'b, 'c) proof_system -> …
```

Prettier toplevel

---

src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt4753_specific.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt4_specific.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt6753_specific.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt6_specific.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/common.cpp
src/libsnark.ml
src/snark.ml

This unifies the bindings for getting the coefficients for the MNT weierstrass curves so that we can switch easily between the curves and deletes some crufty old bindings.

unify the bindings for getting mnt curve coefficients

---

src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt4753_specific.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt4_specific.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt6753_specific.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt6_specific.cpp
src/libsnark.ml

I made a stupid error using the wrong prefixes in the bindings. I wrote a unit test that should prevent anyone from making this error again by checking that the curve generator and coefficients are at least consistent with each other. 
I will make a follow up pr swapping which G1/G2 module is in Mnt4/Mnt6, which I think makes more sense.

Fix error in the group bindings

---

src/as_prover.ml
src/as_prover.mli
src/checked.ml
src/run_state.ml
src/snark0.ml
src/snark_intf.ml
src/typ.ml
src/types.ml

This PR
* adds the `Direct` constructor to `Checked.t`
* adds `make_checked` to `Snark_intf.Run`
* implements `constraint_count` for `Direct` and uses the same technique to provide `constraint_count` in `Run`.

Add a Direct constructor to Checked.t

---

src/snark_intf.ml

The original PR for this went out in parallel with the imperative API, must have missed this in the merge.
With this, the imperative API gets:
```ocaml
let compute x y =
exists Field.typ
~compute:As_prover.(
let%map x = read Field.typ x
and y = read Field.typ y
in
add x y))
```

Expose Let_syntax within As_prover.(...)

---

examples/tutorial/dune
examples/tutorial/tutorial.ml

This fixes #24 (and maybe also #22).
The tutorial is now broken up into smaller steps:
* checked computations -- using `Checked.Assert.equal` and `Field.Checked.mul`
* setting up `input`, `prove, etc.
* `Boolean.t`s and `Field.Checked.if_`
* `Typ.t`s for passing other types than `Field.t` to `prove` -- focusing on `bool`/`Boolean.t`
* introduce `Typ` module, calculate the sum of a `Field.t list` and check it against the unchecked version
* another example, this time using tuples
* introduce `exists`, use `exists ~compute` to run the unchecked version
* `Request.t`s and `exists ~request` to 'secretly' choose some values from a list
* elaborate `Matrix` example

Rework the tutorial to be slower and cover more material

---

app/reformat-snarky/reformat.ml

One of our `node_modules ` for the website includes a `docs.mli` file which isn't an OCaml interface file. This PR stops us from trying to reformat anything under `node_modules`.

Don't reformat in the node_modules subdir

---

src/camlsnark_c/dune

This reverts PR #135.
Since #135 is now in the Snarky repo's history, we can still load that commit as a submodule to test with `-DPERFORMANCE=on` at any point in the future.

Revert "Turn on PERFORMANCE flag for libsnark (#135)"

---

src/snark0.ml
src/snark_intf.ml

This PR
* adds checking that imperative checked functions aren't run inside `As_prover` blocks
* adds `Prover` to the imperative interface, which expose the `As_prover` functions without being wrapped in a monad.

Monadless As_prover.t

---

examples/imperative_test/imperative_test.ml
src/snark_intf.ml

This PR fixes the type of `make_checked` and adds an example which failed to compile before but should now. @mrmr1993 what do you think of adding a value
```ocaml
val direct : (m : Field.t m -> 'a) -> ('a, _) Checked.t
```
?
Somehow that seems sort of more intuitive to me, but maybe it's bad if we have some new-style code which is written against some explicit run module? Not sure…

fix type of make checked

---

src/snark0.ml
src/snark_intf.ml

This PR fixes monadless `As_prover` code by
* adding an argument to `As_prover.get_state`, to stop `Snark.Run.Make` from generating an error
* tweak the behaviour around setting the `as_prover` state
* fix the `run_prover` function, making it a dual of `eval_as_prover`

Fix running monadless As_prover code

---

src/snark0.ml

This PR stops us from restoring the old state after running a computation in the checked API.
/cc @imeckler

Fix a segfault

---

meja/parser_impl.mly
meja/parsetypes.ml
meja/typechecker.ml

This PR tweaks the typechecker to
* carry the type of patterns in `pattern`
* return a (possibly updated) pattern from `check_pattern`
This lets us update type constraints in patterns when the type is modified on import, which we need for 'magic' types like `field`.

[Meja] Modifiable patterns

---

meja/envi.ml
meja/of_ocaml.ml
meja/parser_impl.mly
meja/parsetypes.ml
meja/tests/magic-field.meja
meja/tests/magic-field.ml
meja/to_ocaml.ml
meja/typechecker.ml
src/snark_intf.ml

This PR
* implements implicit type parameters
* adds an `explicitness` flag to `Tvar` to give us implicit variables
* lifts implicit variables to be implicit type parameters in type declarations
* adds the `TUnfold` type declaration kind, as an immediately-unfolding version of `TAlias`
* adds a `field` type, implemented as a `TUnfold` of an implicit variable
Note: the test includes `let add3` etc., which needs PR #133 to work properly.

[Meja] Magic 'field' type

---

examples/tutorial/tutorial.ml

This PR
* makes the reference unchecked implementation for ex. 3 closer to the expected checked implementation
* tweaks ex. 4 so that debug checking in libsnark doesn't fail in proof generation
* makes sure that we don't inline a `failwith` in ex. 9.
**Edit:**
* tweaks ex. 5 & 6 to use `product` instead of `sum` so that more things are checked
* stops ex. 9 from printing on every run

Tweak tutorial

---

src/snark0.ml
src/snark_intf.ml

This PR adds `generate_auxiliary_input`, which is just `prove` with the proving part removed, for tests.
This is the main component of the runner for tests in #148.

Add generate_auxiliary_input for timing tests

---

src/backend_intf.ml
src/backend_types.ml
src/backend_types.mli
src/libsnark.ml
src/run_state.ml
src/snark0.ml
src/snark_intf.ml
src/vector.ml
src/vector.mli

This PR
- creates a generalised `'a Vector.t` representing a vector of `'a`s
- adds types with phantom parameters in a `Backend_types` module with a module constructor that ties them to the relevant field.
* these types are opaque, so they will not unify (even though they are all secretly `void ptr`s)
- uses this to remove some unnecessary type parameters
This will let us lift more things out of `Snark0` (e.g. `Data_spec` once I pull some more parameters out of `Typ.t`), and also makes it much easier to unify the monadic and imperative APIs -- which will make the imperative API much less inefficient!
Basic sanity check:
```ocaml
let () = ignore Backends.Mnt4.(Linear_combination.Vector.emplace_back (Field.Vector.create ()) (Linear_combination.create ()))
```
```
Error: This expression has …
```

Use phantom types to associate libsnark types with the field

---

src/backend_intf.ml
src/libsnark.ml
src/snark0.ml
src/snark0.mli
src/snark_intf.ml

This PR adds a `message` type and an optional `message` argument to `Proof.create`, `prove` and `verify`, to support messages in BG snarks.
This is an alternative to PR #163.

Add a Proof.message type and an optional message argument to prove/verify

---

src/checked.ml
src/snark0.ml
src/snark_intf.ml
src/types.ml

This PR
- adds a `Reduced` constructor to `Checked.t` that carries a `reduce_to_prover`-ed version of a checked computation as well as the original `Checked.t`
- uses this to create a non-destructive version of `reduce_to_prover` -- ie. you can still use the `Checked.t` for everything, and the `reduce_to_prover` version will only be used for `prove`
This makes using and debugging `reduce_to_prover` much simpler.

Rework reduce_to_prover to keep the original AST

---

src/checked.ml
src/checked_intf.ml
src/snark0.ml
src/snark_intf.ml
src/typ.ml
src/types.ml

~~**NOTE: This PR includes the contents of PR #155. The new commits start at 2306cf9.**~~
This PR creates a functor over `Checked_intf.S` for `Typ`, so that the type of the checked computations in `Typ` and those in the rest of the `Snark_intf.S` match.
*Edit: rebased onto master, which now includes #155.*

Functor Typ.t over Checked_intf

---

src/as_prover.ml
src/as_prover.mli
src/checked.ml
src/checked_intf.ml
src/snark0.ml
src/typ.ml

**NOTE: This PR includes the contents of PRs #155 and #156. The new commits start at 52d01cb2d662c76f669af130c348292901d6ebf7.**
This PR
* extracts `Checked.Runner` into its own functor
* functors `Make_basic` over `Backend_extended.S` and `Checked_intf.Extended`
* generalises `Checked_intf.Basic` and `.S` with a `field` constraint type
It is now easy to create a `Snark_intf.Basic` with any type that implements the `Checked_intf.Basic` interface, which brings us most of the way to faster and better imperative interfaces. Last remaining awkward piece is abstracting `Typ.t` over `Checked.t`, which will come in a separate PR.

Functor over checked

---

src/snark0.ml
src/snark_intf.ml

Just adds a 'staged' for reduce to prover to make it obvious how many arguments you have to pass in to get caching.

staged for reduce_to_prover

---

meja/lexer_impl.mll
meja/parser_impl.mly

This PR adds support for comments to the lexer. At present, these are discarded immediately, and never even reach the parser.

[Meja] Add JS-style comments

---

meja/parser_impl.mly
meja/tests/test.meja
meja/tests/test.ml

This PR adds parsing for the syntax `fun () => {...}` and `f()`.

[Meja] Add parsing for bare function unit argument

---

meja/envi.ml
meja/loader.ml
meja/meja.ml
meja/parsetypes.ml
meja/scripts/run-tests.sh
meja/tests/stdlib.meja
meja/tests/stdlib.ml
meja/to_ocaml.ml
meja/typechecker.ml

This PR
* adds type predeclarations when an as-yet undeclared type shows up in an `.cmi` file
- this happens with co-recursive types (ie. `type t = ... and u = ...`), which the stdlib includes (notably in `camlinternalFormatBasics.mli`)
* fixes a bug where type variables leak between value declarations loaded from `.cmi` files
* loads the OCaml standard library by default
* adds some tests
Edit:
* fixes caching and recursive loads in the loader
* adds the `lazy_t` and `array` primitive types to the initial environment.

[Meja] Load the OCaml standard library by default

---

website/docs/try-it-out.md

Specifically the following: in `check_product`, the preceding `Field.`
unnecessary in `Assert.equal`; references to `check_sum` should be `check_product`;
`dune-project` with a hyphen rather than underscore.

Fix typos in try-it-out doc

---

.dockerignore
Dockerfile

rsync was having some issue copying either _build or website.
we don't need either in the container, so ignore them with
.dockerignore.
additionally, `opam upgrade` does nothing because it's not
using the http opam repo, but a git clone. the repo must be
updated manually.

fix the Dockerfile

---

src/curves.ml
src/dune
src/libsnark.ml
src/snark0.ml

This PR makes unused types a compile-time error, fixes up the places where we have unused types.
This accounts for 11 of the compile-time warnings that flood the output every time we compile snarky.

Set warning 34 (unused type) to be an error, remove unused types

---

src/camlsnark_c/libsnark-caml/depends/libff/libff/common/utils.hpp
src/camlsnark_c/libsnark-caml/libsnark/caml/common.cpp
src/libsnark.ml

This PR
* overrides `printf` in the libsnark code using a preprocessor macro
* calls into our own function for printing
* adds some setters to change the destination of the logging
Currently the hooks are:
* `Snarky.Libsnark.set_printing_stdout ()` - default, print to stdout
* `Snarky.Libsnark.set_printing_off ()` - don't print anything
* `Snarky.Libsnark.set_printing_file "filename.log"` - log to `filename.log`
~~I'm working on a way to pipe the `printf`s through to the coda logger, but the memory story is a bit more complicated there.~~
Edit: added `Snarky.Libsnark.set_printing_fun (fun str -> _)` - passes the string libsnark was trying to print (up to length 1023 characters) to the given function for printing.

Override printf in libsnark, add hooks for updating the destination

---

src/backend_extended.ml
src/backend_intf.ml
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_bn128.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt4.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt4753.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt6.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt6753.cpp
src/libsnark.ml
src/snark0.ml

Recall that an rank 1 constraint has the form A * B = C.
Proving key serialization was incorrect because the "generate keypair" function in libsnark swaps all A and B terms in a constraint system if a certain condition is met. We were not doing this when recreating the constraint system ourselves, which led to creating bad proofs. I have corrected this issue and added a test which failed previously and now passes. Thanks to @deepthiskumar for help debugging.

Fix proving key serialization

---

src/camlsnark_c/dune

This PR turns on the PERFORMANCE cmake flag, which improves prover performance by somewhere in the neighborhood of 20%.

Enable the performance flag

---

src/snark0.ml
src/snark_intf.ml

The new interface in #200 (using `Proof_system`) makes it much safer and easier to use `reduce_to_prover`, as well as giving us much more granularity in where/when we use it.

Stop exposing old reduce_to_prover interface

---

src/snark0.ml

This PR
* fixes the error where the `message` parameter wasn't passed through the `Proof_system.verify` API
* removes the unused internal `run` parameter to `Proof_system.verify`

Use the message argument to verify proofs

---

meja/Makefile
meja/scripts/run-tests.sh

This PR adds `make test-one` to run a single meja test.
To run a test:
```sh
cd meja
FILENAME=test make test-one
```

[Meja] Add a single test runner

---

src/snark0.ml
src/snark0.mli
src/snark_intf.ml

This PR
* adds support for `reduced_to_prover` to the `Proof_system.run_unchecked`/`run_checked`/`check`/`prove` functions via the optional `reduce` parameter
* adds a `reduce` parameter to `Proof_system.create` to generate the reduced version eagerly
* adds a global `set_reduce_to_prover` function, to override default behaviour

Integrate reduce_to_prover with Proof_system

---

meja/src/parser_impl.mly
meja/src/typechecker.ml
meja/tests/list_constructor_override.meja
meja/tests/list_constructor_override.ml

This PR
* treats the list constructors `[]` and `::` as first-class constructors
* fixes the type unification for GADTs with free parameters in their constructors
* adds a test
Note that the last line in the `.ml` test output looks wrong, but the problem lies on the OCaml compiler's pretty printer's side.

[Meja] GADT tweaks

---

meja/src/envi.ml
meja/src/parser_errors.ml
meja/src/typechecker.ml
meja/tests/apply-fail.stderr
meja/tests/implicits-fail.stderr
meja/tests/list_weak_variable.stderr
meja/tests/list_wrong_type.stderr
meja/tests/record_wrong_accessor.stderr
meja/tests/wrong_labelled_arg.stderr
meja/tests/wrong_optional_arg.stderr

This PR
* adds a pretty-printing module
* uses the type pretty-printer for error messages instead of the OCaml pretty-printer
* uses boxes and break hints to better control the formatting of error messages
This will be needed for row-subtyping: if the types do not match, they will need to be printed with the row information added, which we can't do by piping through OCaml.

[Meja] Print meja-style types in error messages

---

meja/src/lexer_impl.mll
meja/tests/comments.meja
meja/tests/comments.ml

This PR adds support for nested comments.
Most importantly, this means that the output of `cmi_to_meja` is now always valid meja code: in some cases, most notably functors, we get nested comments which previously had to be tweaked by hand.
This matches ReasonML's behaviour for comments.

[Meja] Add support for nested comments

---

meja/src/ast_build.ml

This PR cherry-picks some commits from #224, committing only the changes to `Ast_build`, and only when they don't depend on other changes.
Changes are:
* functions for the building remaining types that weren't previously supported
* functions for building type declarations

[Meja] Extend Ast_build to support all types and type_decls

---

src/snark0.ml
src/traversable.ml
src/typ.ml

This PR
- adds higher arity constructors to Traversable
- moves `Typ.Of_traversable` out of `Snark0` and into the `Typ` functor

Move Of_traversable out of Snark0

---

meja/meja.ml
meja/src/envi.ml
meja/src/initial_env.ml
meja/src/loader.ml
meja/src/typechecker.ml

This PR
* moves `Initial_env` into its own module
* re-implements `Initial_env` using `Ast_build`
This makes the initial environment stable under changes to the types in `Parsetypes` by using the `Ast_build` wrapper.

[Meja] Move the initial environment into its own module

---

src/camlsnark_c/dune

Libsnark fails to build on mac currently. This change makes it succeed. We should probably get a mac build on CI soon.

Fix mac build

---

src/camlsnark_c/dune

We need to double escape once for dune -> shell and onces for newlines.

Make lines shorter in dune shell

---

meja/scripts/run-tests.sh

At the moment, sending an interrupt with Ctrl-C just ends the current test, which can be quite frustrating if you didn't mean to run all ~90 tests.
This PR captures the interrupt signal and exits the whole test runner instead.

[Meja] Exit tests when Ctrl-C is pressed

---

meja/src/ast_build.ml
meja/src/envi.ml
meja/src/parser_impl.mly

This PR
* adds converters between the basic location types to `Ast_build.loc`:
- `Location.t`, the type used for error reporting
- `Lexing.location * Lexing.location`, generated by menhir
- `string * int * int * int`, generated by the compiler primitive `__POS__`
* uses the converter to give a useful error location for compiler internal errors, pointing to the code responsible
* uses the converter in place of the function in `Parser_impl`
This makes it much easier to find the source of internal errors, which makes debugging simpler.

[Meja] Internal error locations

---

meja/meja.ml
meja/scripts/run-tests.sh

This PR
* adds a `--compiler-backtraces` flag, to give backtraces without recompiling Meja
* switches the flag on in the tests if the `MEJA_BACKTRACE` environment variable is present

[Meja] Add a --compiler-backtraces flag

---

src/merkle_tree.ml
src/merkle_tree.mli

In this PR, I add a `Tag` to merkle_tree.ml. The tag would be used in the `Get_element` request to determine the target merkle_tree.

Tags for merkle tree

---

src/checked.ml
src/checked_intf.ml
src/snark0.ml
src/snark_intf.ml

This PR implements `handle_as_prover`, which lets us communicate prover-only information into handlers. For example, this reduces the code necessary for merkle tree tags (#246) to:
```ocaml
handle_as_prover ( (* code that calls modify_ref here *) )
As_prover.(
let%map tag = read Tag.typ is_chain_voting in
fun (With {request; respond}) ->
match request with
| Get_element addr ->
(* handler code using the value of tag *)
| _ -> unhandled))
```

Implement handle_as_prover

---

src/camlsnark_c/libsnark-caml/libsnark/caml/caml_bn128.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt4.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt4753.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt6.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt6753.cpp
src/libsnark.ml

This should fix the bug which is causing the proposer to fail in coda. I was calling swap_AB_if_beneficial always after rebuilding a constraint system, but it is in fact not called in the groth-maller key generator, and only in the groth16 key generator. This change it so that for groth-maller we do not call that function on rebuilding a constraint system.

Fix GM bug (don't swap AB)

---

src/camlsnark_c/dune

Tested on macOS, we may need to make more changes to the linux build
later. The biggest change here is explicitly setting `OPT_FLAGS` to not
include `-march=native -mtune=native`, and explicitly turning on
USE_ASM.
I ran transaction-snark-profiler over in Coda both with and without the
OPT_FLAGS override and there is negligible changes in performance
numbers. USE_ASM is what really gets this thing flying.
PERFORMANCE is disable always on macOS because there are errors in the
rest of the build that were always present when it was on.

Builds are portable

---

meja/src/envi.ml
meja/src/typechecker.ml

This PR
- adds an `is_subtype` method
- uses `is_subtype` to check whether instances are general enough to catch all the cases necessary
* this fixes a bug (which made my computer OOM :sweat_smile:) that would recursively try and fill an implicit variable of type `'a` with an instance of type `poly('a)`.

[Meja] Only resolve implicit arguments when the instance is a supertype

---

meja/src/codegen.ml
meja/src/envi.ml
meja/src/type0.ml
meja/src/typechecker.ml
meja/src/typeprint.ml
meja/src/untype_ast.ml

This PR separates depth from `Tvar`. This is necessary for
* compatibility with #221, for managing which local type declarations are in scope or not
* unifying implicits fully to fix the quirks in #255 
* making the level mutable, for tracking visibility and interacting with the mutable type description I'm working on
This should be a no-op. The only behavioural change is in `Type0.typ_debug_print`, which I use for my debugging only.

[Meja] Store a depth for all types

---

src/camlsnark_c/libsnark-caml/libsnark/zk_proof_systems/ppzksnark/r1cs_bg_ppzksnark/r1cs_bg_ppzksnark.tcc
src/snark0.ml

This PR fixes two bugs in the implementation of the BG SNARK. It adds a test confirming that the BG SNARK does work.
See the top of [page 7 here](https://eprint.iacr.org/2018/187.pdf) for the spec for the verifier which this implements.

Fix BG bugs

---

meja/src/envi.ml
meja/src/type0.ml
meja/src/typechecker.ml

This PR
* adds `Type0.fold`/`iter`
* replaces some recursive functions with recursive calls to `Type0.fold`
- this makes it easier to add and tweak the representation of types, since these functions touch a smaller surface of the `type_desc` type
This will have the largest impact in #258, where the co-recursor for rows could be completely replaced with a single one for fold for these functions.

[Meja] Iterators

---

meja/src/codegen.ml
meja/src/envi.ml
meja/src/type0.ml
meja/src/typechecker.ml
meja/src/typeprint.ml
meja/src/typet.ml
meja/src/untype_ast.ml

This PR
* switches to carrying the type declaration for a variant directly, instead of carrying its ID
* removes global variant registration from the environment
Doing this makes several things much simpler:
* temporary type declarations (#221) are much more straightforward to manage, since they will just be garbage-collected when the types using them are recast to generalised type variables
* unfolding types during unification/subtype checking can be done without reference to the environment
- this will make it a lot less cumbersome and error-prone to type matches over GADTs properly
* type substitutions (for functors/local modules) can be much more simply implemented
This is a no-op.
Edit: Updated to
* make `type_desc` mutable
* updates types in-place during type declaration import, so …

[Meja] Carry type declarations in variants instead of the ID

---

meja/meja.ml
meja/meji/boolean.meji
meja/meji/field.meji
meja/meji/typ.meji
meja/src/envi.ml
meja/src/parser_impl.mly
meja/src/type0.ml
meja/src/typechecker.ml
meja/tests/typ-explicit.meja
meja/tests/typ-explicit.ml

This PR
* fixes importing types from signatures
- specifically, this change ensures that type variables with the same name are considered to be the same type variable (a2b552b)
* adds some interface files containing the declarations that `Typ.t` deriving relies on
- ae9471e and 4b948cd
- these will be lazily loaded at some point, using roughly the same strategy as for `.cmi` files
* fixes a bug where the expected type was being compared with variable names before the implicit arguments have been stripped from them
- e4b1483 
* adds parsing support for type annotations in expressions
- 59c0989
- this was already used internally in the `fun (...) : ... => {...}` syntax and for `Typ.t` generation over in #255, this just exposes it properly
- the syntax explicitly requires enclosing `(` and …

[Meja] Unify implicits with free variables in the common case

---

meja/src/envi.ml
meja/src/typechecker.ml
meja/tests/type-alias-unification.meja
meja/tests/type-alias-unification.ml

This PR changes the unification algorithm so that alias types with phantom parameters will still unify, and adds a test.
This matches OCaml's behaviour.

[Meja] Always unfold type aliases when unifying

---

meja/src/ast_types.ml
meja/src/pprint.ml

This PR
* stops the pretty-printer from wrapping `()` in parentheses (ie. `(())`)
* reworks expression printing to use mostly 'cut' hints, so that fewer spaces are inserted and fewer lines wrap
- this is particularly noticeable in nested `switch` statements (like the generated code for request handlers), which ended up pretty unreadable with about 1 line per syntax tree node

[Meja] Fix expression printing

---

src/snark0.ml
src/snark0.mli

This PR adds stateless versions of the imperative interface functor and the type `m` of module expressions from this functor.

Add a stateless version of the imperative interface

---

meja/src/envi.ml
meja/src/typechecker.ml
meja/tests/type_variable_scoping.meja
meja/tests/type_variable_scoping.ml

This PR fixes an oversight where type variables would get unified across toplevel definitions.
Before this PR, the test added would have generated a unification error between `bool` and `int` on the type variables `'a`, `'b`.

Ensure that type variables don't get unified across distinct statements

---

meja/meja.ml
meja/src/ast_types.ml
meja/src/envi.ml
meja/src/loader.ml
meja/src/typechecker.ml
meja/tests/resolve_type_names.meja
meja/tests/resolve_type_names.ml

This PR
* carries the current path to a module in the module
- I am going to use this to identify multiple 'versions' of modules in the stdlib: one version for the checked stuff, and one version for the prover stuff
* fixes some bugs I uncovered about module hierarchies
* keeps a log of the most recent names for type constructors in the scope stack
- I am going to use this to cast the names to the appropriate types in the OCaml code, so that e.g. under the hood the prover and checked `field` types are distinct (but named the same in Meja), and then they get disambiguated to the 'best recent name', which will be `Field.t`/`Field.Unchecked.t` as appropriate.
* adds a simple test to check that this is working as intended.

[Meja] Resolve type names before OCaml printing

---

src/libsnark.ml

This stops us from needing to regenerate the R1CS, which seems to mismatch with the key when we do so.

Stop stripping the R1CS from the proving key before converting to string

---

src/snark0.ml

This PR evaluates the `check` part of each `Typ.t` when we are
* generating a proof using `prove` in the old (ie. non-`Proof_system`) API, and
* the proving key has a cleared R1CS, which we need to regenerate.
Previously, these would have been skipped entirely, which meant that the R1CS wouldn't have any constraints corresponding to the inputs. I think this was the culprit behind codaprotocol/coda#2559.
This was overlooked because
* when we refactored `prove` etc. into a unified `run` function, it was then able to generate constraints for checked computations
* when the R1CS-stripping hack was added, the right constraint system was generated through `run` for the computations themselves, but **no constraints were added for the input's `Data_spec.t`**
* the R1CS-stripping only gets …

Evaluate input constraints when generating the r1cs in prove

---

src/libsnark.ml

This reduces our cache size by ~50% for coda.

Strip R1CS's again

---

src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt4753_specific.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt4_specific.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt6753_specific.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt6_specific.cpp
src/libsnark.ml

I almost committed a bad bug involving converting curve points from the network into affine coordinates (and was only saved by a quickcheck test :)).
This is a bad class of bugs, so I think we should make conversion to affine coordinates by default return an option. I included a `to_affine_exn` function, but there aren't that many uses in our codebase so maybe we should just get rid of it entirely.

Make failure case when converting to affine more explicit

---

meja/dune
meja/meja.ml
meja/ocaml/dune
meja/ocaml/loader.ml
meja/ocaml/of_ocaml.ml
meja/ocaml/to_ocaml.ml
meja/src/dune

This PR separates the code that interfaces directly with the `ocaml-compiler-libs` library from the rest of the typechecker. Eventually, all of the OCaml codegen will be moved here, and the typechecker will just typecheck ASTs and the environment.
This also frees up a lot of module names for the typechecker, which will make naming things much less painful.

[Meja] Split out OCaml code

---

bitstring_lib.opam
fold_lib.opam
interval_union.opam
meja.opam
ppx/snarky_module.ml
ppx/snarkydef.ml
ppx_snarky.opam
snarky.opam
snarky_bench.opam
tuple_lib.opam

This PR
* updates the `*.opam` files to reflect the actual version constraints
* changes the code generated by `snarky_ppx` to produce `Stdlib` instead of `Pervasives` (which is deprecated in 4.08)
There are still compilation errors in meja with 4.08, but they're slightly more involved because it interfaces with `ocaml-compiler-libs`. I haven't found a good way to support 4.07 and 4.08 simultaneously yet, so (for now) those migrations will have to happen at the time of the 4.07->4.08 change..

Add 4.08 support to snarky

---

src/backend_types.ml
src/backend_types.mli
src/bool_vector.ml
src/ctypes_foreign.ml
src/dune
src/int_vector.ml
src/libsnark.ml
src/long_vector.ml
src/vector.ml
src/vector.mli

This PR functors the commonly used FFI bindings over `Ctypes.FOREIGN`, so that we can generate C stubs using the Ctypes API and remove the majority of our libffi overhead.
This doesn't do the actual generation yet, that will be in a follow-up PR.

Functor the core FFI bindings over Ctypes.FOREIGN

---

src/pedersen.ml
tuple_lib/double.ml
tuple_lib/quadruple.ml
tuple_lib/triple.ml

This PR makes the checked Pedersen module take its parameters in affine coordinates so it doesn't spend time converting them to affine on the fly (which is super costly).
I also added "map" functions for tuples because I found myself wanting them when fixing up coda to build against this.

Affine params

---

src/backend_extended.ml
src/checked_runner.ml
src/cvar.ml
src/snark0.ml

This PR
* reworks `Cvar.eval` to avoid a `Field.Mutable.copy` when reading a variable
* reworks `project` (and thus also `pack`) to be faster.
In particular, the changes to `project` mean that:
* the number of allocations made by `Cvar.eval` is halved
- these are now just the allocations made when reading from the vector
- the number of multiplications and additions is unchanged
* no C++ allocations within project/pack`
* there are no field computations within project/pack

Faster Cvar.eval and project/pack

---

src/as_prover.ml
src/as_prover_intf.ml
src/snark0.ml
src/snark_intf.ml
src/typ.ml

This will let us avoid the hacks that we used in Meja during the
conference to handle string passing etc. between the worlds.
This slightly overloads the behaviour of `As_prover.Ref.t`, but for Meja's
purposes this will be invisible to the user anyway. Perhaps more
importantly, this type can be special-cased to give good error messages
when the user tries to use prover-generated data outside of a prover
block.
Generating code that uses `snarkable` will be slightly more awkward,
since we need to track when the same variable is read and then
re-stored, but it should be possible to make it work.  The important case
that this supports is code like:
```reason
...
let x = {data: 1000f, aux_data: 50};
let x = Prover { {x.. data= x.data * 10f} };
...
```
where the int `aux_data` might be used …

Add Typ.t's for non-snarkable values

---

meja/src/pprint.ml

This ensures that code parsed as e.g.
```reason
...
let x = {let x = ref 1; incr x; incr x; let x = !x; x;};
x;
...
```
gets correctly printed so that it can be parsed again.
Currently, master prints
```reason
...
let x = (let x = ref 1; incr x; incr x; let x = !x; x);
x;
...
```
which will not parse.

[Meja] Print curly braces around bracketed Pexp_seq/Pexp_let statements

---

meja/ocaml/of_ocaml.ml
meja/ocaml/to_ocaml.ml
meja/src/ast_build.ml
meja/src/parser_impl.mly
meja/src/parsetypes.ml
meja/src/parsetypes_iter.ml
meja/src/parsetypes_map.ml
meja/src/pprint.ml
meja/src/typedast.ml
meja/src/typedast_iter.ml
meja/src/typedast_map.ml
meja/src/typet.ml

This PR
* removes an unused field `type_id` from `Parsetypes`
* removes an unused field in `Parsetypes.Ctor_record`
* removes `Parsetypes.typ_debug_print`
* adds an iterator and a mapper for each of `Parsetypes` and `Typedast`
The mapper will most importantly be used to convert Meja names into OCaml names in the typed AST, and OCaml names to Meja names when converting back to a parsed AST.
The `Typedast` iterator will be used to generate an environment from a typed AST serialised to a file, as well as making it cleaner and less error-prone to extract information from it for codegen (e.g. `request`, where the current method is extremely brittle).
At the moment, I don't have a planned use for the `Parsetypes` iterator, but I expect it will be useful for debugging parser problems, which I …

[Meja] AST iterators/mappers

---

examples/merkle_update/merkle_update.ml
src/merkle_tree.ml
src/merkle_tree.mli

The Merkle tree code here used `hash` or `compress` to indicate where hashes were combined for the hash of an interior node.
Change that to `merge`, which is the terminology used in the `CodaProtocol/coda` codebase.
Tested with `make` and `make tests`.

Rename compress/hash to merge

---

meja/meja.ml
meja/src/envi.ml
meja/src/ident.ml
meja/src/ident.mli
meja/src/parsetypes_iter.ml
meja/src/type0.ml
meja/src/typechecker.ml
meja/src/typedast.ml
meja/src/typedast_iter.ml
meja/src/typedast_map.ml
meja/src/typeprint.ml
meja/src/typet.ml
meja/src/untype_ast.ml

This PR introduces `Ident.t` for identifiers in the typechecker and the environment. It
* defines an `Ident` module (with an opaque type, since we'll want to adjust it later) for unique values with (potentially) identical user names
* adds `Ident.Table.t`, a kind of map where we can find the value associated with an `Ident.t` by either its name (a `string`) or directly using the `Ident.t`
* uses `Ident.Table.t`s in place of the maps in the environment
* uses `Ident.t`s for all of the types in `Type0`
This uniqueness information is currently thrown away, pending a restructuring of the `Envi.t` search mechanism. I'm going to do this separately, since it will involve a bigger change to make it OCaml compatible and start rejecting e.g.
```reason
module A = {
module B = {
let x = 15;
};
}; …
```

[Meja] Unique identifiers

---

src/number.ml

This PR fixes a copy-paste error which made `Number.(<=)` return false for equal values.

Fix Number.(<=)

---

meja/src/parsetypes_map.ml
meja/src/type0_map.ml
meja/src/typedast_map.ml

This PR
* adds a mapper for `Type0`
- importantly, it preserves equality unless subvalues have changed
* uses it to map values from `Type0` within `Parsetypes_map`/`Typedast_map`
This is needed for adding implicit arguments to types when importing type declarations as `Typedast.type_decl`s.

[Meja] Add a Type0 mapper

---

src/snark0.ml
src/snark_intf.ml
src/typ_monads.ml

This PR
* adds a helper function to `Typ_monads.Read` to convert a normal read value into one that returns the underlying `Cvar.t`s
* uses it to implement `unsafe_read_cvars`, which evaluates the read on a series of field zeros and dumps the `Cvar.t`s
* implements a generic `if_` with a `Typ.t` argument
This is safe to use as long as
* the `Typ.t` is consistent between its `alloc` and `read` fields
- we have a variety of other problems if this doesn't hold
* the `read` field of the `Typ.t` will accept a value comprised of only field zeros
- this is true for all of our built-ins, including `Enumerable.Make`
- there's a warning mentioning in the function's doc-comment

Add a generic if_ function

---

meja/meja.ml
meja/ocaml/loader.ml
meja/src/envi.ml
meja/src/ident.ml
meja/src/ident.mli
meja/src/parsetypes.ml
meja/src/parsetypes_iter.ml
meja/src/parsetypes_map.ml
meja/src/path.ml
meja/src/pprint.ml
meja/src/type0.ml
meja/src/typechecker.ml
meja/src/typedast.ml
meja/src/typedast_iter.ml
meja/src/typedast_map.ml
meja/src/typeprint.ml
meja/src/typet.ml
meja/src/typet.mli
meja/src/untype_ast.ml

This PR
* adds the `Path.t` type, describing a unique path to any object in the environment via `Ident.t`
* changes the environment search so that it constructs a `Path.t` as it locates a `Longident.t`
* migrates the majority of the constructors in `Typedast` from`Longident.t` to `Path.t`
This includes a couple of hacks:
* the `Path.t` that we should pass to a functor is converted to a `Longident.t`
- we can implement functors much more cleanly using the typed AST mapper once #324 and #320 are in, so this will disappear along with all the other functor hacks soon anyway
* we bail out instead of attempting to map over a `TForward` in the parsetree
- `TForward` should never appear in the user-generated parsetree
- it's trivial to link it back in once #324 has landed
From here, we can …

[Meja] Add a Path.t type built from Ident.t's

---

meja/ocaml/of_ocaml/of_ocaml_4.07.1.ml
meja/ocaml/to_ocaml.ml
meja/src/ast_build.ml
meja/src/codegen.ml
meja/src/envi.ml
meja/src/parser_impl.mly
meja/src/parsetypes.ml
meja/src/parsetypes_iter.ml
meja/src/parsetypes_map.ml
meja/src/pprint.ml
meja/src/type0_map.ml
meja/src/typechecker.ml
meja/src/typedast.ml
meja/src/typedast_iter.ml
meja/src/typedast_map.ml
meja/src/typet.ml
meja/src/typet.mli
meja/src/untype_ast.ml
meja/tests/magic-field.ml

This PR
* moves the `Type0.*` conversion in `Untype_ast` into a `Type0` submodule
* renames some awkwardly-named `Parsetypes` constructors so that they don't clash with `Type0`'s
* removes the type forward-declarations from `Parsetypes`
- only the `Type0` versions are ever used
* removes some unused constructor/record arguments
* adds `type_expr`, `type_desc`, etc. to `Typedast`, along with an extra `type_type` parameter that refers to the typechecker's `Type0.type_expr`
* make `Typet.import` return a `Typedast.type_expr`
* giving the wrong number of implicit arguments (not currently exposed by the parser) now throws a type error
This work is incomplete -- we should be using these `Typedast` versions in all places in the typed AST that we originally parsed a type -- but we need the mapper …

[Meja] Expose a typed version of Parsetypes.type_expr, etc.

---

meja/src/type0_map.ml

At present, the `Type0` mapper re-generates `Path.t`s unconditionally, which causes it to also re-generate any values that contains a `Path.t` field, etc.
This PR fixes the behaviour so that we only generate a new value if the subvalues have changed.

Make Type0_map.default_mapper.path preserve equality

---

src/monad_sequence.ml
src/snark0.ml
src/snark_intf.ml

This PR
* adds a `Boolean.Array` module to `Snark_intf.*`
* adds a `Monad_sequence.Array` functor
* removes some unnecessary `Boolean.` prefixes for types in the `Boolean` module
This should make it much more straightforward to use `array`s, as well as making the matrix part of the tutorial much easier (although you would still need to construct `Monad_sequence.Array` for `Typ_monad.Store`/`Read`/`Alloc` manually to create the `Typ.t`).

First-class support for arrays

---

src/camlsnark_c/libsnark-caml/depends/libff/libff/algebra/fields/fp4.hpp
src/camlsnark_c/libsnark-caml/depends/libff/libff/algebra/fields/fp6_2over3.hpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_curve.cpp.template
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt.cpp.template
src/libsnark.ml

This PR tweaks the dummy verification  key backend function to have any `Fqk` elements be "all ones" so to speak. The reason is the following:
When hashing a verification key, we want to compress it down to as much data as possible.
Say Fqk is F_{(p^e)^2} = F_{p^e}[X] / (..).
An element `a + b X` of Fqk is called unitary if `a^2 + b^2 = 1`. Fqk elements in the verification key are unitary, which means the `b` coordinate can be deduced from the `a` coordinate up to a sign. So, we can compress `a + b X` down to `a` plus a bit. The bit that we use (because extracting it is convenient in the circuit) is the parity of the "real part" of `b`. But this bit is only enough information to figure out the sign if `b` has non-zero real-part. So, the real part of `b` should be nonzero and we have an …

Tweak the dummy verification key function

---

bitstring_lib/bitstring.ml
bitstring_lib/bitstring.mli

Adds a simple function for padding a bitstring with zeroes. If it's LSB first we pad at the end and if it's MSB first we pad at the beginning.

Add padding functions to bitstring lib

---

interval_union/interval_union.ml
interval_union/interval_union.mli
src/libsnark.ml
src/pedersen.ml
src/snark0.ml
src/snark_intf.ml

This adds a few convenience functions. Namely infix arithmetic, an "append" function for pedersen sections, and a parity function for field elements.

A few convenience functions

---

meja/ocaml/of_ocaml/of_ocaml_4.07.1.ml
meja/ocaml/of_ocaml/of_ocaml_4.08.0.ml
meja/ocaml/to_ocaml.ml
meja/src/ast_build.ml
meja/src/codegen.ml
meja/src/envi.ml
meja/src/parser_impl.mly
meja/src/parsetypes.ml
meja/src/parsetypes_iter.ml
meja/src/parsetypes_map.ml
meja/src/pprint.ml
meja/src/type0.ml
meja/src/type1.ml
meja/src/typedast.ml
meja/src/typedast_iter.ml
meja/src/typedast_map.ml
meja/src/typeprint.ml
meja/src/typet.ml
meja/src/untype_ast.ml

The parameter is never anything but `Explicit` any more, so there is no need to keep it. This PR also removes some code in `Typet` that wasn't being executed because of this.
Implicit parameters to types will be removed as part of PR #366; those changes are not included here to avoid redundancy.

[Meja] Remove Tvar explicitness parameter

---

meja/src/envi.ml
meja/src/type1.ml
meja/src/typechecker.ml

This PR
* implements backtracking
* uses backtracking to implement `unifies`
* uses the new `unifies` function (and an extra check) to implement implicit instance searches
- this also lets us remove `is_subtype`

[Meja] Implement backtracking

---

meja/ocaml/of_ocaml/of_ocaml_4.07.1.ml
meja/ocaml/of_ocaml/of_ocaml_4.08.0.ml
meja/ocaml/to_ocaml.ml
meja/src/envi.ml
meja/src/parsetypes.ml
meja/src/parsetypes_iter.ml
meja/src/parsetypes_map.ml
meja/src/pprint.ml
meja/src/typechecker.ml
meja/src/typedast.ml
meja/src/typedast_iter.ml
meja/src/typedast_map.ml
meja/src/untype_ast.ml

This fixes some weird errors that were showing up when loading some `.cmi` files, and removes a hack that was added to try and catch some of them.

[Meja] Seperate Mty_alias and Mty_ident

---

meja/meja.ml
meja/tests/recursive-type.stderr

It will still get loaded lazily as needed, but will also be replaced by proper meja interface files.

[Meja] Stop autoloading snarky from .cmi files

---

src/libsnark.ml

This just alters the `message` type for the BG snark to be an array of field elements, for compatibility with the use of the Poseidon hash function.

Tweak for using Poseidon

---

meja/src/envi.ml
meja/src/type1.ml
meja/src/typechecker.ml

This PR replaces the existing variable instance set-up (a map from type ID to the instance) with the new `Tref` constructor. This
* makes finding type instances 'free', which speeds up the typechecker
* simplifies the implementation of `flatten` and stops it from depending on the environment
* makes type unification actually `backtrack`able without using the `variable_instances` overwrite hack
* adds some more sanity checks to make sure that we're not adding instances to non-type-variables
* preserves the user-provided names of types whenever possible
* removes some of the complications with variable instances from type stitching

[Meja] Use mutability for unification

---

src/checked.ml
src/checked_intf.ml
src/checked_runner.ml
src/snark_intf.ml
src/types.ml

This PR adds the `Lazy` constructor to `Checked.t`.
This gives us a straightforward way of caching without needing to jerry-rig it each time, like we've been trying to do with bit unpacking. The obvious use cases are:
* `choose_preimage_*`/`unpack`
* possibly `Field.Checked.compare` (where we don't necessarily always need the constraints for the 'less-than' condition)
For exceptions raised when a lazy value is forced during normal evaluation, the error message will look like this:
```
Uncaught exception:
Snarky.Checked_runner.Runtime_error(_, _, _, _)
Encountered an error while evaluating the checked computation:
(Your error here)
Label stack trace:
labels
to
the
error
Lazy value forced at:
labels
to
the
lazy
value
forcing
Raised at file "blah.ml", line blah, characters blah
Called from …
```

Lazy values

---

src/camlsnark_c/libsnark-caml/libsnark/caml/caml_curve.cpp.template
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_curve.h.template
src/camlsnark_c/libsnark-caml/libsnark/zk_proof_systems/ppzksnark/r1cs_se_ppzksnark/r1cs_se_ppzksnark.hpp
src/libsnark.ml

This PR adds `Proof.dummy : unit -> Proof.t` for all proof systems. This gives us consistent values that we can use to test that serialisations of proofs are stable from Coda.
/cc @psteckler

Add dummy proofs

---

meja/src/envi.ml
meja/src/type0.ml
meja/src/type0_map.ml
meja/src/type1.ml
meja/src/typechecker.ml
meja/src/typeprint.ml
meja/src/typet.ml
meja/src/typet.mli
meja/src/untype_ast.ml
meja/tests/recursive-type.stderr

Note: this PR includes #389.
This PR
* adds a `tdec_ret` field to type declarations, which specifies the (stitched) type that instances of the type declaration should be instantiated with
* adds an optional parameter to `Typet.TypeDecl.import` to specify which type the imported declaration's type should be stitched to
I have been working on a different strategy for conversions (ie. `Typ.t` generation) using a dedicated AST and a new type `Tconv`. This will let us drop the `Codegen` and actually call `Typet.TypeDecl.import` with this new parameter, as well as properly generating `Typ.t`s for tuples, etc. That PR will depend on this, but this is broken out because that work already has a particularly large diff footprint, and is still incomplete.

[Meja] Enable stitching in type declarations

---

src/libsnark.ml

I am doing this change because decoding the binary_version of proof is taking too much time for the protocol and it is one of the reason for long async cycle during bootstrap. After talking to Izzy, he suggested me to move the `subgroup_check` to `verify` in order to make decoding faster.

moving the subgroup check to verify function

---

snarkyjs/bin/index.js
snarkyjs/index.js
src/backend_extended.ml
src/backend_intf.ml
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_curve.cpp.template
src/libsnark.ml
src/snark0.ml
src/snark_intf.ml
src/toplevel.ml

This PR tweaks the `Proof_system` interface to
* by default, store the r1cs hash with the proving key
* reject the proving key if the r1cs hash doesn't match
- this causes a fresh key to be generated
This also tidies up the `snarkyjs` node command, so the names match the `js_snarky` -> `snarkyjs` change, and so that the default set-up steps work again with:
```bash
sudo npm install -g path/to/snarkyjs
cd new/project/directory
snarkyjs init ; npm link snarkyjs
node index.js
```

Store R1CS hash with keys by default, re-generate when reading

---

src/camlsnark_c/libsnark-caml/libsnark/caml/caml_curve.cpp.template
src/libsnark.ml

I am swapping Groth16 with BG18 in Coda, so now Groth16 proofs will be broadcast on the network. So, we need to perform the subgroup check when verifying and we would like to have control over the wire representation of Groth16 proofs.
This PR adds an OCaml record representing Groth16 proofs so we can have control over the wire format, and performs the subgroup check in verification.

OCaml record representation for groth16 proofs

---

sponge/intf.ml
sponge/params.sage
sponge/sponge.ml
sponge/sponge.mli

This just reorganizes a bit of code in the sponge library, adds back some ocaml codegen for the parameter generation which is specific to coda, and adds in parameter generation for the Tock/MNT6 curves, which is needed for switching Bowe--Gabizon18 with Groth16.

Sponge reorg

---

snarkette/bowe_gabizon.ml
snarkette/groth16.ml
snarkette/mnt6753.ml
snarkette/mnt6_80.ml

This PR adds Groth16 to snarkette. It is based on the bowe--gabizon module, with some code removed essentially.
I also fixed a bug in the bowe gabizon code (which was fixed in an old branch that never got merged).

add groth16 to snarkette

---

src/libsnark.ml

Currently, the types `Proving_key.t`, `Verification_key.t` and `Keypair.t` are opaque in `Libsnark.*.Default` and `Libsnark.*.Groth16`. This PR tweaks the creation of the `Groth16` modules so that the types alias to those in `Default`.
This fixes a compilation error in Coda.
Edit: Specifically this:
```
File "lib/coda_base/transition_system.ml", line 247, characters 44-68:
Error: This expression has type Tick_backend.Verification_key.t
but an expression was expected of type
Curve_choice.Tick_full.Groth16.Verification_key.t
```

Build Groth16 with existing keys types

---

meja/src/envi.ml
meja/src/typechecker.ml
meja/tests/module-scoping.stderr
meja/tests/record_wrong_accessor.stderr
meja/tests/recursive-type.stderr
meja/tests/wrong_labelled_arg.stderr
meja/tests/wrong_optional_arg.stderr

This PR
* adds a mechanism for generating distinct type variable names
* uses this mechanism to assign distinct type variable names to each type in `Typechecker` error messages
- This makes several ambiguous/unclear error messages clearer, most notably `tests/recursive-type.stderr`
This will also form a necessary part of printing out module signatures when performing multi-file builds: we will need to functor the module over the snarky interface *and the signatures of all modules on which it depends* in order to allow switching between fields and proof systems easily, and so we need to be able to print signatures including type variables unambiguously.

[Meja] Generate unique type variable names for printing

---

scripts/test-website-build.sh

A package update has broken the website test in CI. This PR changes the way docusaurus is initialised so that it pulls in the 'locked' versions set in `package-lock.json`, so that CI starts passing again.

Use `npm ci` to test website builds

---

snarky_integer/integer.ml
snarky_integer/integer.mli

This PR
* fixes the bound checks on `Snarky_integer.add`/`mul`
- previously, these were comparing `log2(upper_bound) < field_size`, giving a maximum upper bound of `2^(2^field_size_in_bits)` :sweat_smile:
* adds doc-comments
* adds `Integer.to_bits_opt` as an alternative to `to_bits_exn` that doesn't raise
* adds `Integer.subtract_unpacking`
- we compute (and cache) `to_bits` on the result to ensure that it is `>= 0`, since it is more useful than a comparison on the arguments
- this is called `subtract_unpacking` rather than just `sub` to draw attention to how constraint-heavy it is on large arguments
- this feature was requested by @psteckler

Snarky_integer.subtract_unpacking and other tweaks

---

snarky_integer/integer.ml
snarky_integer/integer.mli

This PR
* adds `Integer.subtract_unpacking_or_zero`
* adds a label to `Integer.subtract_unpacking`
- this makes for a better label backtrace when the constraint in `subtract_unpacking` fails.

Add Integer.subtract_unpacking_or_zero

---

meja/src/envi.ml
meja/src/type1.ml
meja/src/typechecker.ml
meja/tests/prover-test.ml
meja/tests/tri-stitching.meja
meja/tests/tri-stitching.ml

This PR
* switches to using `Treplace` for instantiating type variables for copying
- we already do this for all other copies, it's better to have a unified mechanism
- this also fixed a bug where slight behavioural differences between `Tref` and `Treplace` were causing instances not to be found (see `meja/tests/prover-test.ml`)
* changes the tri-stitching copying algorithm to handle cases of `'variable -> type1 <-> type2` stitching properly
- the new test checks this; previously, this test would crash the typechecker with an `AssertionError`
- there are also new stronger checks that ensure we meet these invariants everywhere

[Meja] Fix tri-stitching

---

app/reformat-snarky/reformat.ml

This speeds up `make format`/`make check-format` by ignoring all of the generated website files.

[TRIVIAL] Don't ocamlformat files under website/

---

snarky_curve/snarky_curve.ml
snarky_universe/group.ml

This PR implements an optimized fixed-base scalar multiplication.
The algorithm is as follows. Say g is the base and s = s_0, s_1.. s_{2(n-1)} is the scalar. We also require an "unrelated base" h. That is, a group element with no knowable discrete log relationship to g. A good way of getting this is hashing g with a random oracle.
Let as_int(b0, b1) = b0 + 2 * b1.
Let shift_i = 2^i * h.
Let t_i = shift_i + (2^{2 i} * as_int(s_{2i}, s_{2i+1})) * g
Let shifted_result be the sum of the t_i, using `add_unsafe`. This is acceptable because the shifts make it so that no terms can have colliding x coordinates.
Let shift = sum_{i=0}^{n-1} t_i = (2^n - 1)*h.
Let result = shifted_result - shift, where the subtraction is performed using "safe" addition.
One note: The `lookup_point` function is …

Implement optimized fixed base scalar mul

---

snarkette/fields.ml
snarkette/nat.ml
snarkette/nat_intf.ml

In Coda,`Snark_params.Tick.Field.t` has the code generated by `deriving hash`.
To build a nonconsensus node, we'd like the `Fq.t` types from snarkette to have the same code definitions. And so this PR.

Add deriving hash for Nat in snarkette

---

snarkette/fields.ml

Add `random` function to snarkette to match snarky, for use in Coda nonconsensus code.

Add random function to snarkette

---

src/backend_extended.ml
src/backend_intf.ml
src/camlsnark_c/bindings/vector.mli
src/checked_runner.ml
src/constraint_system.ml
src/cvar.ml
src/field_intf.ml
src/libsnark.ml
src/libsnark_r1cs_constraint_system.ml
src/run_state.ml
src/snark0.ml
src/snark_intf.ml

This PR prepares snarky to work with the new curve backends.
Previously backend_extended had a bunch of code which used libsnark specific functionality to implement a few functions on constraint systems (e.g., computing the digest) Now, a backend is expected to provide those functions itself. A functor has been added for generating those functions from a libsnark backend.
Also, in the new backend, the constraint system is not a pointer but an ocaml value. As such, instead of the `run_state` having a pointer in it, I have replaced it with a "poor man's object" of a constraint system. That is, an abstractly typed value paired with a module with the necessary functions on that type (`add_constraint`, `set_primary_input_size`, etc.)

Pare down backend

---

snarkette/dune
snarkette/fields.ml
snarkette/nat.ml
snarkette/nat_intf.ml
src/snark0.ml
src/snark_intf.ml

Two changes:
- add `gen_uniform_incl` to the snarky interface, so we can generate values within specified bounds (in Coda, `Private_key` generated numbers within bounds, then coerced them to a field value; seems better to do this "natively")
- change the `snarkette` `bin_io` serialization of fields to match the `snarky` serialization, which is to stuff bytes in a `Bigstring.t`; that seems to require right 0-padding to a word boundary (determined by comparing serializations from Coda nonconsensus code, which relies on snarkette, with the consensus code)

add gen_uniform_incl; snarkette bin_io matches snarky

---

src/cvar.ml

This adds an important optimization to Cvar which is that a 0 constant term is the same as no constant term.

0 constant term is same as none

---

src/camlsnark_c/camlsnark_linker_flags_gen.ml
src/camlsnark_c/libsnark-caml/CMakeLists.txt
src/camlsnark_c/libsnark-caml/depends/libff/CMakeLists.txt
src/camlsnark_c/libsnark-caml/depends/libff/libff/CMakeLists.txt
src/camlsnark_c/libsnark-caml/depends/libff/libff/algebra/fields/bigint.tcc
src/camlsnark_c/libsnark-caml/libsnark/CMakeLists.txt

This PR modifies libff to use sodium for generating random field elements. This fixes a potential vulnerability on certain old platforms

Use libsodium for randomness

---

snarky_curve/snarky_curve.ml

This PR implements Daira's fast scalar multiplication algorithm from [here](https://github.com/zcash/zcash/issues/3924).

Add daira's fast scalar multiplication

---

snarkette/fields.ml

The `gen` created by `Make_fp` uses a zero lower bound. That's unsuitable for some uses, in particular, for the `Inner_curve.Scalar.t` type in Coda's nonconsensus crypto definitions.
We add `gen_incl`, which lets you set lower and upper bounds for a Quickcheck generator.
Really, we should have done this all along, since we already paired `gen_uniform` with `gen_uniform_incl`.

Add gen_incl to fields in snarkette

---

src/snark0.ml
src/snark_intf.ml

PR #468 added `gen_incl` to snarkette fields.
In Coda, the `Field_extensions` library uses a snarkette interface in a way that `gen_incl` becomes required in snarky `Field`.
This PR adds `gen_incl` to `Field`, which now satisfies that interface.

Add gen_incl to Field

---

src/camlsnark_c/camlsnark_linker_flags_gen.ml

Coda already statically links `libsodium`, so this change prevents executables from the coda repo built with snarky trying to dynamically load a `libsodium.so`.

Statically link libsodium

---

group_map.opam
group_map/dune
group_map/field_intf.ml
group_map/group_map.ml
group_map/group_map.mli
snarky_curve/dune
snarky_curve/snarky_curve.ml
sponge/intf.ml
sponge/sponge.ml
sponge/sponge.mli

This PR
- moves the group map library into snarky and uses it to produce an "unrelated base" for the purposes of the optimized in-snark exponentiation
- adds the bn382 sponge inputs to `sponge`

Move in groupmap and sponge

---

src/backend_extended.ml
src/checked_runner.ml
src/constraint.ml
src/libsnark_r1cs_constraint_system.ml

This makes the constraint type extensible. A backend will implement a subset of the variants. This is to permit adding PLONK-type constraints in upcoming work.

Extensible constraint type

---

meja.opam

because meja/src/compiler_internals contains files only for
4.07.1 and 4.08.0.

meja requires at least OCaml 4.07.1

---

group_map.opam
sponge.opam

Before this commit, `opam pin .` showed warnings like
```
[WARNING] Failed checks on sponge package definition from source at git+file:///home/<snip>/snarky/snarky#master:
warning 47: Synopsis (or description first line) should start with a capital and not end with a dot
```

Remove periods from opam package synposis

---

src/monad_let.ml

monad_let.ml contained similar definitions of `Make`, `Make2` and `Make3` functors. Actually, `Make` is a special case of `Make2`, which in turn is a special case of `Make3`.
This PR uses `Make3` to define the other two.

Monad let simplifications

---

meja.opam

This PR replaces `jbuilder` with `dune` in the build command of meja, following a suggestion in #477.

Replace jbuilder with dune as builder of meja

---

src/camlsnark_c/libsnark-caml/libsnark/caml/caml_curve.cpp.template
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_curve.h.template

These bindings are unused, removing them reduces the size of the library and improves compile time.

Remove protoboard, SHA256 bindings

---

sponge/sponge.ml
sponge/sponge.mli

This PR adds a squeze_field function to the bit sponge that squeezes a full field element.

add squeeze_field function to sponge

---

src/backend_extended.ml

This stops using the fast project function as it was incompatible with the zexe backends. @mrmr1993 do you think I should just remove the commented out unit test or is it worth keeping it in the file?

Remove fast project

---

sponge/sponge.ml
sponge/sponge.mli

This allows us to use 256 for the current large curves, but 128 for the
tweedle curves.
Most importantly, this allows us to bump snarky in current coda develop.

Take high_entropy_bits as a parameter for Bit_sponge

---

src/number.ml
src/number_intf.ml

This adds to the snarky number module
- a function for computing `(n, k) -> n mod 2^k`.  It computes using the identity `n mod m = n - m * floor(n / m)`
- a function for computing `(n, k) -> ceil(n / 2^k)`. It computes using the identity `ceil(n / m) = if n % m = 0 then floor(n / m) else floor(n / m) + 1`.

Add "mod" and "ceil div" functions to snarky number (for powers of 2)

---

src/camlsnark_c/snark_caml_bn128/dune
src/camlsnark_c/snark_caml_mnt298/dune
src/camlsnark_c/snark_caml_mnt753/dune

Fixes a bug in the embedded bash build scripts in `snarky/src/camlsnark_c/snark_caml_*/dune` that prevents compile on MacOS - causes libtool to choke on popd because the prev line ends with \\ (continuation)

camlsnark_c: fix bash build cmds on macos

---

src/base/snark0.ml

This PR fixes false-positive exceptions that I've been encountering while testing for MinaProtocol/mina#6579.

Reset registered runners when exceptions are raised during evaluation

---

src/base/snark0.ml
src/base/snark_intf.ml
src/base/typ.ml

This allows us to create types easily using derivers and modules. For most cases, this will eventually allow us to avoid hlist machinery altogether and simply do `Typ.mk_typ (module Foo)`.

Add mk_typ functions to convert a packed module to a Typ.t

---

snarky_curve.opam
snarky_curve/BUILD.bazel
snarky_curve/dune
snarky_curve/snarky_curve.ml

Mina doesn't build without snarky_curve here. Tests aren't re-added and need to be moved to https://github.com/o1-labs/libsnark-ocaml

re-adding snarky_curve (needed for mina)

---

sponge/sponge.ml
sponge/sponge.mli

Without this, the new parameters (pasta_p_3) cannot be accessed from outside the sponge library.

making new params available to users of sponge lib

---

src/base/dune

Help the poor OCaml reader who is trying to figure where dependencies are coming from :)

make bigint dependency explicit

---

sponge/dune
sponge/sponge.ml
sponge/test_vectors/dune
sponge/test_vectors/fp_3.json
sponge/test_vectors/hash_function.ml
sponge/test_vectors/hex.ml
sponge/test_vectors/main.ml
sponge/test_vectors/three_wire.json

I introduced an off-by-one error here: https://github.com/o1-labs/snarky/pull/585/commits/120fcdae5b697a46b481bd84d435b825dcc4e699#diff-6ece204f52dc5d5f99d41c96cb239b21e8968325f0e6e937aa1eea2be1b1dc57L187
Interestingly, I was thinking about that change these days and the fact that without test vectors I had potentially introduced a bug. Well, looks like I did it. 
So this PR fixes the bug and introduces test vectors (generated by this PR in the marlin repo: https://github.com/o1-labs/marlin/pull/103)
Yeah, you can run `dune runtest` to run these.
- we're copy/pasting code from the hexstring lib: https://github.com/mimoo/hexstring because hexstring is not compatible with 4.07.1. As we move to a higher version of OCaml I should be able to remove this (cc @psteckler )
- we're also …

[sponge] fix bugs + test vectors

---

sponge/intf.ml
sponge/sponge.ml

This reverts commit 9dddcca58c02835109d0341f08cf1157c22cd427.
After discussion with @imeckler it looks like this won't work with some of the more abstract circuit fields.

Revert "Use monomorphic comparison for tests"

---

sponge/test_vectors/main.ml

Use string equality instead of polymorphic equality to compare test vector names, to allow compilation with recent Jane Street libraries.

String equality for test vector names

---

sponge/test_vectors/main.ml

More replacements of polymorphic equality with string equality.
Verified that unit tests for `snarky` fully run with OCaml 4.11.2 with these changes (which, regrettably, I didn't do with #591).

More string equality instead of poly equality

---

src/base/snark0.ml
src/base/snark_intf.ml

This PR adds support for 'public outputs' from circuits, allowing circuits to return a value that will be exposed as part of the public input to the proof, and exposing that returned value to the caller.
This enables the more natural modelling of circuits as functions that take and return some data, and enable us to remove duplicate code where we construct the 'input' both inside and outside of the circuit. Importantly, this will allow SnarkyJS circuits to return the constructed `Parties.t` without needing to run the logic twice.

Add support for public outputs

---

snarkette/nat.ml

This PR makes a single change so that `snarky` can be built with core v14.

Compatibility with core v14

---

snarkette/fields.ml

Add a version number to the `bin_shape_t` for snarkette field type, and an admonishing comment, so that the Mina version linter based on shapes will be able to detect serialization changes.

Version field bin_shape

---

dune

Silence the new warning introduced by OCaml 4.14 for implementation files without interface files.

Silence new 'missing mli' warning

---

src/base/snark0.ml
src/base/snark_intf.ml

This PR removes `Data_spec.t` from the snarky interface, and replaces all uses with a single `input_typ:_ Typ.t` argument.
The commits in this PR are structured so as to do the minimum amount of work at each step, while still achieving compilation. Interested reviewers can follow the process of applying the conversion step-by-step.

Remove `Data_spec.t`

---

ppx/snarkydef.ml
snarky_curve/snarky_curve.ml
src/base/enumerable.ml
src/base/snark0.ml
src/base/snark_intf.ml

This PR makes the `Checked.t` type abstract in `Snark_intf`.
This will allow us to swap out the implementation of `Checked.t` for some other one (e.g. snarky.rs) without any changes on the Mina side.
This PR also updates ppx_snarky, adding the ability to expose paths on the `%snarkydef` and `%with_label` annotations, to direct them at the appropriate module if required.
Note that this leaves the type of `check` in the `Typ.t` as `Checked_ast.t`, because it was surprisingly annoying to make it work on the Mina side. Instead, this PR introduces `make_checked_ast` and `run_checked_ast` functions, which allow converting between the types and the AST type.

Make Checked.t abstract

---

ppx/snarkydef.ml
src/base/checked_ast.ml
src/base/checked_intf.ml
src/base/checked_runner.ml
src/base/knapsack.ml
src/base/number.ml
src/base/pedersen.ml
src/base/snark0.ml
src/base/snark_intf.ml

This PR adds some unit arguments to functions, to make the imperative and monadic APIs consistent.

Add unit arguments to functions

---

src/base/checked_ast.ml
src/base/checked_runner.ml
src/base/cvar.ml
src/base/run_state.ml
src/base/run_state.mli
src/base/snark0.ml

This PR makes `Run_state.t` opaque. This should make it much easier to attach the rust backend, since we don't have to pass the actual `Run_state.t` OCaml structure back-and-forth.

Make Run_state.t opaque

---

src/base/ast_runner.ml
src/base/checked_ast.ml
src/base/checked_intf.ml
src/base/checked_runner.ml
src/base/snark0.ml
src/base/snark0.mli

This PR extracts the logic for the AST interpreter from the rest of the `Checked_runner` module. Most notably, this also restructures the runner so that it will function correctly over any `Checked.t` implementation.
As a side-effect, the `Runtime_error` type can no longer access the full stack of labels, so we have to build them incrementally and generate the error message at the end. This also tweaks the backtrace printing so that we don't elide intermediate backtraces any more (which has long been an ask!)

Extract the AST interpreter from the rest of the checked runner

---

src/base/backend_extended.ml
src/base/backend_intf.ml
src/base/cvar.ml
src/base/runners.ml
src/base/snark0.ml
src/base/snark0.mli
src/base/snark_intf.ml

Looks like the `Var` module might have been a vestige of the past? It's currently nothing more than an `int`:
https://github.com/MinaProtocol/mina/blob/develop/src/lib/crypto/kimchi_backend/common/var.ml#L3

remove Var module

---

src/base/backend_extended.ml
src/base/backend_intf.ml
src/base/snark0.mli

This PR removes the `R` module inside `Bigint`, a holdover from the long-dead libsnark backend
Corresponding Mina changes in [this branch](https://github.com/MinaProtocol/mina/compare/feature/snarky-remove-bigint-R-module?expand=1).

Remove unnecessary Bigint.R module

---

sponge/intf.ml
sponge/sponge.ml
sponge/test_vectors/hash_function.ml

With the goal of auto-generating all constants which define Poseidon behaviour from the OCaml source (for https://github.com/o1-labs/snarkyjs/pull/572), this PR adds three such constants to `sponge/intf.ml`, namely, `alpha`, the `state_size` and the `rate`

Add defining constants to Sponge Intf

---

src/base/checked_runner.ml
src/base/run_state.ml
src/base/run_state.mli
src/base/snark0.ml

We change the state monad to take into account pure computations (computations that do not need to be ran in a circuit because it only involves constants)
```diff
- type ('a, 'f) t = 'f Run_state.t -> 'f Run_state.t * 'a
+ type ('a, 'f) t = Pure of 'a | Function of ('f Run_state.t -> 'f Run_state.t * 'a)
```
We also make sure that `is_running` is set to `false` in the global at ALL time except when we're running a circuit (e.g. in user-facing functions like `constraint_system` and `generate_witness`). This means we have to set it to `false` at the end of running these functions.
Perhaps we should additionally:
* always check when using functions like `constraint_system` and `generate_witness` that `is_running` is set to `false` at the start (otherwise we're in the middle of a …

fix the runner for pure computations

---

website/website/pages/api/.gitattributes

This removes the generated *.html files from the Linguist statistics.

website: Mark API docs as linguist-generated

---

src/base/checked.ml
src/base/snark0.ml
src/base/utils.ml

to fix a bug I mention in the comment here https://github.com/o1-labs/snarky/pull/752#issuecomment-1376600672 
I'll copy/paste the issue:
running into some error, that can be reproduce from mina by doing:
```
make snarkyjs
cd src/lib/snarky_js_bindings/test_module 
npm i
node simple-zkapp-mock-apply.js
```
the issue is an `assert_equals` function that does not handle constant variables correctly.
The reason is that it's using what's in `checked.ml` (which is "impure" as it adds a constraint):
```ocaml
let assert_ ?label c = add_constraint (Constraint.override_label c label)
let assert_equal ?label x y = assert_ (Constraint.equal ?label x y)
```
whereas we want to use the wrapper that's introduced in `utils.ml` (which handles the constant correctly, and keep the logic "pure"):
```ocaml
let …
```

move assert_equals to checked

---

src/base/run_state.ml
src/base/run_state.mli
src/base/snark0.ml
src/base/snark_intf.ml

this fixes a number of issues detected by the tests in https://github.com/MinaProtocol/mina/pull/12627. More specifically:
* make sure that the global state is reset between API calls
* make sure that API calls that raise exceptions clean the state
* make utility functions handle pure functions gracefully

fix imperative interface handling of global state

---

src/base/runners.ml
src/base/snark0.ml
src/base/snark_intf.ml

This PR adds versions of `run_and_check` and `check` that don't capture the exception in an `Or_error.t`, instead allowing the exception itself to propagate. This allows e.g. SnarkyJS to handle the errors more directly.

Add run_and_check_exn and friends

---

src/base/backend_extended.ml
src/base/snark0.ml
src/intf/field.ml

supports https://github.com/o1-labs/snarkyjs/pull/1073
- make computation of field size bits lazy so it doesn't block web page loading
- `Z.testbit` is very slow. In the near future I hope to put more performant js implementations in place, and changes like this one will no longer be necessary
- use `Field.to_string` and `Field.of_string` from the bindings instead of implementing it via `to_bignum_bigint` and `Bignum_bigint.to_string`
- this just makes sense, because it gives us the flexibility of optimizing the implementation in JS
- just a glimpse of many future similar changes that I'd like to do, avoiding the zarith bigint stubs which are slow

Snarkyjs: Reduce loading time

---

src/base/as_prover0.ml
src/base/as_prover_intf.ml
src/base/checked_runner.ml
src/base/constraint.ml
src/base/request.ml
src/base/request.mli

Instead of throwing JS errors, which are costly because they collect a full stack trace, this changes some core parts of snarky to throw strings instead. Throwing strings is very fast, and this change leads to a huge speedup during witrness generation, see https://github.com/o1-labs/o1js/pull/1092

Avoid costly errors in JS witness generation

---

src/base/snark0.ml
src/base/snark_intf.ml

This adds a small `Async_generic` module to snarky which functors over a `Promise` (any `Monad` actually) module and implements an async handler for a `unit Promise.t Request.t`, needed by https://github.com/MinaProtocol/mina/pull/15305
This could be easily extended in the future to support more general async versions of `exists`

Async requests

---

src/base/run_state.ml
src/base/run_state.mli
src/base/runners.ml

This PR adds IDs to the snarky run state, and uses them to check that the state wasn't clobbered by some concurrent circuit execution.

Be aggressive about checking state consistency

---

src/base/as_prover0.ml
src/base/as_prover_intf.ml
src/base/checked.ml
src/base/checked_intf.ml
src/base/checked_runner.ml
src/base/runners.ml
src/base/snark0.ml
src/base/snark_intf.ml
src/base/typ.ml
src/base/types.ml
src/base/utils.ml
src/base/utils.mli

This PR bundles a few changes. This can be broken into smaller pieces by commit if needed.
The goal of this PR is to remove the generalisation over `Field.t` from `Checked.t` and `As_prover.t`, allowing us to hoist `Typ.t` from the global implementation in `Types`. The result is a unique `Typ.t` type for each instantiation of snarky, allowing us to generate it from any checked backend (and in particular from a rust backend).
To achieve this, we
* create a new helper functor `Types.Make_types`
* remove the free field argument from `As_prover.t`
* replace uses of the concretised types with those from the shared `Types` module signature
* remove some unused or now-unnecessary type and functor machinery.
The recommended way to review this PR is to 'ignore whitespace' in the GitHub UI (or …

Remove polymorphism from `As_prover.t`, hoist `Typ.t`

---

src/base/as_prover0.ml
src/base/as_prover_intf.ml
src/base/checked.ml
src/base/checked_intf.ml
src/base/checked_runner.ml
src/base/runners.ml
src/base/snark0.ml
src/base/snark_intf.ml
src/base/typ.ml
src/base/types.ml
src/base/utils.ml
src/base/utils.mli

This PR finally makes `Typ.t` concrete, removing the remaining free parameters. It is now possible to hoist the `Typ.t` code to sit entirely above the definitions of `Checked.t` and `As_prover.t`, letting them be plugged in as arbitrary concrete types.

Remove type parameters from `Typ.t`

---

src/base/backend_extended.ml
src/base/backend_intf.ml
src/base/checked.ml
src/base/checked_intf.ml
src/base/checked_runner.ml
src/base/constraint.ml
src/base/constraint_system.ml
src/base/run_state.ml
src/base/run_state.mli
src/base/run_state_intf.mli
src/base/runners.ml
src/base/snark0.ml
src/base/snark0.mli
src/base/snark_intf.ml
src/base/utils.ml
src/base/utils.mli

This PR builds on https://github.com/o1-labs/snarky/pull/858, delivering on a large part of the promise of previous iterations: this allows us to define a constraint-system-specific constraint enum instead of overloading the snarky one. In particular, this gives the ability to have safe rust FFI types for constraint system generation, by only allowing the specific constraints that it supports.
As part of the pre-work that built up to this, we have also ensured that a `Typ.t` for any particular constraint definition is compatible with only the constraint systems that support it, ensuring that we get better type safety for OCaml / JS too.

Abstract over the specific `Constraint.t` type used by the backing constraint system

---

website/docs/readme.md

Using `https://` instead of `git@` ensures the command works for everyone. The `git@` format requires configured SSH keys, while `https://` works out-of-the-box, making it more accessible for beginners.

Why use `https://` instead of `git@`?**

---

.github/workflows/docs.yml
scripts/build-website.sh

This pull request includes two changes: enabling manual triggering of the documentation workflow and commenting out the removal of a JavaScript file during the website build process which is causing the workflow to fail.
Workflow configuration updates:
* [`.github/workflows/docs.yml`](diffhunk://#diff-9cf2000c53760d837a449f874e53f792819108d3a4bf346336d0f7d082deae2cR7): Added `workflow_dispatch` to allow manual triggering of the documentation workflow.
Website build script changes:
* [`scripts/build-website.sh`](diffhunk://#diff-3093f21b5e4c5867821079fa9a72c26ddd97f42a6c022fa384a3bfa2598575daL8-R8): Commented out the line that removes `highlight.pack.js` from the API documentation directory, the file doesn't exist anymore. I'll investigate deeper with ability of manually triggering the …

Fix Docs Workflow

---

.github/workflows/docs.yml

This pull request updates the GitHub Actions workflow configuration to use a newer version of the `peaceiris/actions-gh-pages` action.
* [`.github/workflows/docs.yml`](diffhunk://#diff-9cf2000c53760d837a449f874e53f792819108d3a4bf346336d0f7d082deae2cL30-R30): Updated the `Deploy` step to use `peaceiris/actions-gh-pages@v4` instead of `v3`.

Bump up gh-pages action 

---

bitstring_lib/bitstring.mli

This PR fixes the type signature of the `of_msb_first` function to correctly reference `'a Msb_first.t` instead of `'a Lsb_first.t`.

Fix type declaration

---

snarky.opam

This PR adds `alcotest` to `snarky.opam` as a test dependency.

Add alcotest dependency to snarky

---

ppx/dune
ppx_snarky.opam

It is also not support for OCaml >= 5.1

ppx: remove unused ppx_tools
