README.md

Redos #6 for new updates.
Thanks @pirapira for the idea!

Clarify build and exec of examples in README

---

bench.opam
bench/dune
bench/field_project.ml
bench/main.ml
bench/runner.sh
src/bigint_intf.ml
src/libsnark.ml
src/snark0.ml
src/snark_intf.ml

```
┌───────────────────────────────────────────────────────┬──────────┬─────────┬───────────┬───────────┬────────────┐
│ Name                                                  │ Time/Run │ mWd/Run │  mjWd/Run │  Prom/Run │ Percentage │
├───────────────────────────────────────────────────────┼──────────┼─────────┼───────────┼───────────┼────────────┤
│ [bench/field_project.ml] projecting 256-bit list      │   8.86us │  4.94kw │    26.53w │    26.53w │      3.43% │
│ [bench/field_project.ml] slow projecting 256-bit list │ 258.20us │ 75.86kw │ 4_616.51w │ 4_616.51w │    100.00% │
└───────────────────────────────────────────────────────┴──────────┴─────────┴───────────┴───────────┴────────────┘
```

Faster Field.project

---

meja/typechecker.ml

@nholland94 Merged #54 before I saw your comment, this does the `bind_none` thing.

Simplify by using bind_none

---

meja/envi.ml
meja/parser_impl.mly
meja/parsetypes.ml
meja/tests/tuples.meja
meja/tests/tuples.ml
meja/to_ocaml.ml
meja/typechecker.ml

This PR adds support for tuples to the parser and typechecker.

[Meja] Tuples

---

src/snark0.ml
src/snark_intf.ml

This moves the test-util functions into snarky

Move test utils into snarky

---

meja/dune
meja/envi.ml
meja/parser_impl.mly
meja/parsetypes.ml
meja/tests/match.meja
meja/tests/match.ml
meja/to_ocaml.ml
meja/typechecker.ml

This PR adds records and constructors to patterns and expressions in Meja

[Meja] Add records and constructors

---

src/curves.ml
src/dune
src/knapsack.ml
src/snark0.ml

* remove unused opens 
* alter dune warn list to error on unused opens

removed unused opens

---

meja/envi.ml
meja/lexer_impl.mll
meja/parser_impl.mly
meja/parsetypes.ml
meja/tests/apply-fail.stderr
meja/tests/open-types.meja
meja/tests/open-types.ml
meja/tests/record_wrong_accessor.stderr
meja/to_ocaml.ml
meja/typechecker.ml

This PR implements parsing and typechecking for open types.

[Meja] Add support for open types

---

src/camlsnark_c/libsnark-caml/depends/libff/libff/algebra/curves/curve_utils.hpp
src/camlsnark_c/libsnark-caml/depends/libff/libff/algebra/curves/curve_utils.tcc
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_bn128.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt4.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt4753.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt6.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt6753.cpp
src/libsnark.ml

This PR adds a windowed scalar multiplication function to libsnark and adds bindings to libsnark.ml. I also fixed (yet another error) in the bindings and made a type opaque that accidentally wasn't before so it shouldn't happen again.

Windowed exponentiation

---

website/docs/installation.md
website/docs/overview.md
website/docs/readme.md
website/docs/try-it-out.md
website/website/sidebars.json
website/website/siteConfig.js

This PR adds some introductory pages to the website

Add some pages to the website

---

src/camlsnark_c/dune

Turn on PERFORMANCE flag for libsnark

---

src/camlsnark_c/libsnark-caml/libsnark/caml/caml_bn128.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt4.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt4753.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt6.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt6753.cpp
src/field_intf.ml
src/libsnark.ml
src/snark0.ml

Adds mutating versions of +, *, -

Mutating field operations

---

src/snark0.ml
src/snark_intf.ml

this makes it hard to give useful errors!

check: don't erase the error into a bool

---

examples/tutorial/tutorial.ml
src/curves.ml
src/cvar.ml
src/field_intf.ml
src/knapsack.ml
src/pedersen.ml
src/snark0.ml
src/snark_intf.ml

no infix module

---

src/camlsnark_c/libsnark-caml/libsnark/caml/caml_bn128.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt4.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt4753.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt6.cpp
src/camlsnark_c/libsnark-caml/libsnark/caml/caml_mnt6753.cpp
src/libsnark.ml

Just some errors that I made which cropped up when trying to instantiate the BG functor.

BG bugfixes

---

meja/meja.ml
meja/tests/implicits.ml
meja/tests/list.ml
meja/tests/magic-field.ml
meja/tests/match.ml
meja/tests/modules.ml
meja/tests/open-types.ml
meja/tests/operator_names.ml
meja/tests/patterns.ml
meja/tests/records.ml
meja/tests/test.ml
meja/tests/tuples.ml
meja/tests/type_declarations.ml

This PR
* generates the snarky preamble
* adds some command line options to disable and change its contents

[Meja] Snarky preamble

---

meja/envi.ml
meja/of_ocaml.ml
meja/parsetypes.ml
meja/to_ocaml.ml
meja/typechecker.ml

This PR
* adds parsing for functors from OCaml
* implements functors in the environment
* adds resolvers for functor `Lidents` (e.g. `Make(A)(B).Make(C).D`)

[Meja] functors

---

meja/meja.ml

This PR shows the usage text when no filename is given, instead of failing with an error.

[Meja] Show usage when no files are given

---

.circleci/config.yml
meja/ast_build.ml
meja/dune
meja/envi.ml
meja/lexer_impl.mll
meja/loader.ml
meja/meja.ml
meja/of_ocaml.ml
meja/parser_impl.mly
meja/parsetypes.ml
meja/scripts/run-tests.sh
meja/tests/request.meja
meja/tests/request.ml
meja/tests/request.stderr
meja/to_ocaml.ml
meja/typechecker.ml

This PR implements Snarky requests and handlers.
This also fixes some small bugs along the way, and makes some failure cases stricter to catch errors earlier.

[Meja] Requests and handlers

---

src/backend_extended.ml
src/backend_intf.ml
src/libsnark.ml
src/snark_intf.ml

Does what it says on the tin. Needed for an upcoming PR.

Make proof binable instead of stringable.

---

src/dune

6 - Label omitted in function application
39 - Unused rec flag

Make warnings 6 and 29 errors

---

src/libsnark.ml

This just adds "accessors" for the various components of the BG SNARK.

Add proof accessors for BG SNARK

---

src/camlsnark_c/libsnark-caml/libsnark/caml/caml_curve.cpp.template
src/libsnark.ml

This adds dummy verification keys for the libsnark backends.

Dummy verification keys

---

interval_union/interval_union.ml

More descriptive Interval_union error messages

---

src/pedersen.ml

This PR makes the unpacked Pedersen digest a `Bitstring.Lsb_first.t` instead of a `list`.

Use Bitstring.Lsb_first for unpacked Pedersen digest

---

src/checked_runner.ml

This moves the error handling into a dedicated function, and wraps each call into user code with it.

Make run tail-recursive again

---

examples/anonvote/anonvote.re
snarky_integer.opam
snarky_integer/dune
snarky_integer/integer.ml
snarky_integer/integer.mli
snarky_integer/util.ml
snarky_universe.opam
snarky_universe/dune
snarky_universe/hash.ml
snarky_universe/intf.ml
snarky_universe/membership_proof.ml
snarky_universe/merkle_tree_unchecked.ml
snarky_universe/snarky_universe.ml

This adds 
- integers to snarky universe (just copying over snarky_integer from coda)
- an unchecked hash and Merkle tree, both copied over from snarky-cryptojs

Unchecked hash and merkle tree + integers

---

snarkyjs/index.js
src/toplevel.ml

Expose OCaml backtraces in snarkyjs errors

---

snarky_universe/intf.ml
snarky_universe/snarky_universe.ml

add select function

---

snarky_integer/integer.ml
snarky_integer/integer.mli
snarky_universe/snarky_universe.ml

I am taking over imeckler's this PR https://github.com/CodaProtocol/coda/pull/3144.
I am just porting his original change snarky.

Porting the changes made by ihm

---

src/camlsnark_c/libsnark-caml/libsnark/caml/common.cpp

Make time formatting OCaml compatible

---

src/typ.ml

This PR just adds some typs for larger size tuples.

Add typs for tuple4, tuple5

---

src/merkle_tree.ml
src/merkle_tree.mli

...without computing the hashes for the intermediate root

two merkle tree modifications per request

---

snarkette/fields.ml

We added `gen_uniform` to snarky proper some time ago.
This PR adds the same functionality to snarkette. The Quickcheck generators for Coda's `Non_zero_curve_point` and `Public_key` use this, so we'll need this, if we want the nonconsensus versions of those modules to offer the generators.

Add gen_uniform to Snarkette

---

website/docs/try-it-out.md

The Snarky interface has been updated to take in a proof_state and this change updates the try-it-out.md page to reflect that change.

DOCS: Update try-it-out.html for updated Snarky interface.

---

snarky_curve/snarky_curve.ml

This adds if_ to snarky_curve for non-shifted curve points

if_ in snarky curve

---

src/cvar.ml

and instead use an immutable argument to `go` function.

Avoid mutable can_mutate_state

---

snarky_bench.opam

Replace jbuilder with dune in snarky_bench build

---

group_map/bw19.ml
group_map/dune
group_map/field_intf.ml
group_map/group_map.ml
group_map/group_map.mli
snarky_curve/snarky_curve.ml

This copies over group map updates from the coda repo that were already approved.

Group map updates

---

snarky_curve/snarky_curve.ml

This PR renames `scale` to `scale_fast` so that the original, more flexible scale function is still available.

rename scale to scale fast

---

src/snark0.ml

This evaluates if_ statically if the condition is a constant

optimization for constant condition in if_

---

snarkette/tweedle.ml

Constants taken from [here](https://github.com/o1-labs/zexe/tree/master/algebra/src/tweedle).

add tweedle curves and fields to snarkette

---

.gitignore

gitignore (emacs) backup files

gitignore backup files: *~

---

sponge/sponge.ml
sponge/sponge.mli

Add
- a function to construct a bit sponge "manually"
- a function to access the sponge inside

Add two simple functions to bit sponge

---

bitstring_lib/BUILD.bazel
bitstring_lib/BUILD.bzl
ctypes_foreign/BUILD.bazel
ctypes_foreign/BUILD.bzl
fold_lib/BUILD.bazel
fold_lib/BUILD.bzl
group_map/BUILD.bazel
group_map/BUILD.bzl
h_list/BUILD.bazel
h_list/BUILD.bzl
h_list/ppx/BUILD.bazel
h_list/ppx/BUILD.bzl
interval_union/BUILD.bazel
interval_union/BUILD.bzl
ppx/BUILD.bazel
ppx/BUILD.bzl
snarkette/BUILD.bazel
snarkette/BUILD.bzl
sponge/BUILD.bazel
sponge/BUILD.bzl

* bitstring_lib
* ctypes_foreign
* fold_lib
* group_map
* h_list
* interval_union
* ppx
* snarkette
* sponge

Bazel update revised PR 1: top-level simple pkgs

---

snarky_cuda/BUILD.bazel
snarky_cuda/BUILD.bzl
snarky_curve/BUILD.bazel
snarky_curve/BUILD.bzl
snarky_curve/tests/BUILD.bazel
snarky_curve/tests/BUILD.bzl
snarky_integer/BUILD.bazel
snarky_integer/BUILD.bzl
snarky_signature/BUILD.bazel
snarky_signature/BUILD.bzl
snarky_universe/BUILD.bazel
snarky_universe/BUILD.bzl
src/base/BUILD.bazel
src/base/BUILD.bzl
src/intf/BUILD.bazel
src/intf/BUILD.bzl
tuple_lib/BUILD.bazel
tuple_lib/BUILD.bzl

* snarky_cuda
* snarky_curve
* snarky_integer
* snarky_signature
* snarky_universe
* src/base  (snarky_backendless)
* src/intf  (snarky_intf)

Bazel update revised PR 2: snarky pkgs

---

app/reformat-snarky/reformat.ml
sponge/intf.ml
sponge/sponge.ml

fixes https://github.com/MinaProtocol/mina/pull/8913

[sponge] fix test

---

.circleci/config.yml
opam.export
src/base/backend_intf.ml
src/base/snark0.ml
src/base/snark_intf.ml

This PR removes some definitions and interfaces that aren't directly used anywhere. This is a no-op.

Remove some unused definitions and interfaces

---

src/base/snark_intf.ml

This PR separates the boolean interface from the other definitions, specialising it for each of the monadic and imperative APIs.

Extract boolean interface from Snark_intf.*

---

src/base/snark_intf.ml

This PR extracts the common constraint interface from the imperative and monadic APIs into a common signature

Extract constraint interface from Snark_intf.*

---

src/base/checked_runner.ml

This PR removes some unused aliases.

[Trivial] Remove unused aliases

---

src/base/snark0.ml

This PR simplifies some code after `Data_spec.t` was removed in https://github.com/o1-labs/snarky/pull/649.

Tidy up runners code

---

src/base/snark0.ml
src/base/snark0.mli

not used anywhere in Mina either

remove dead code

---

.github/workflows/docs.yml

This fixes an oversight in https://github.com/o1-labs/snarky/pull/600.

Stop updating docs from PRs!!

---

snarky_curve/snarky_curve.ml
src/base/as_prover.ml
src/base/as_prover.mli
src/base/as_prover_intf.ml
src/base/ast_runner.ml
src/base/checked_runner.ml
src/base/enumerable.ml
src/base/runners.ml
src/base/snark0.ml
src/base/snark_intf.ml
src/base/typ.ml
src/base/utils.ml

this is the output of @imeckler and I pairing!

Make Checked generic instead of using Checked_ast

---

src/base/snark0.ml

Let's see if this fix a bug in snarkyJS

[Field.Assert] make lte pure if we're comparing constants

---

src/base/checked_runner.ml
src/base/runners.ml
src/base/snark0.ml
src/base/snark_intf.ml

- Add run_and_check_exn and friends
- respect Runner.eval_constraints

Add run_and_check_exn and friends - RAMPUP

---

src/base/cvar.ml
src/base/cvar.mli
src/tests/backend.ml
src/tests/dune
src/tests/fermat.ml
src/tests/snarky_tests.ml

- relax the `Extended` Field intf for `Cvar` to the basic `S`
- added a prime field backend for testing
- added a simple example circuit test which uses this backend

Add simple backend for testing and simple test circuit

---

snarkette/dune

Remove num
